/*$Id: ph_input_struct_writer.h 892 2006-03-10 15:24:59Z rcatwood $*/
/* AUTOGENERATED header file for write structure routines */
#ifndef ph_input_struct_writer_h
#define ph_input_struct_writer_h
extern void write_ph_input_struct_values(FILE * fp,struct ph_input_struct *Struct_Ptr);
#endif /* ph_input_struct_h /*