/*$Id: ph_input_struct_reader.h 892 2006-03-10 15:24:59Z rcatwood $*/
/* AUTOGENERATED header file for structure input routines */
#ifndef ph_input_struct_reader_h
#define ph_input_struct_reader_h
extern void free_input(struct ph_input_struct *Struct_Ptr);
extern void input_ph_input_struct_values(char * filename,struct ph_input_struct *Struct_Ptr);
#endif /* ph_input_struct_reader_h */
